export function exportToOpenAPI(endpoints, projectName = "Generated API") {
  const spec = {
    openapi: "3.0.0",
    info: {
      title: projectName,
      version: "1.0.0",
      description: "REST API specification generated by AI REST API Designer"
    },
    paths: {},
    components: {
      securitySchemes: {
        BearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT"
        }
      }
    }
  };

  endpoints.forEach(ep => {
    const path = ep.route;
    if (!spec.paths[path]) {
      spec.paths[path] = {};
    }

    const method = ep.method.toLowerCase();
    
    // Extract parameters in path
    const parameters = [];
    const paramMatches = ep.route.match(/\{([^}]+)\}/g);
    if (paramMatches) {
      paramMatches.forEach(match => {
        const name = match.substring(1, match.length - 1);
        parameters.push({
          name: name,
          in: "path",
          required: true,
          schema: { type: "string" }
        });
      });
    }

    spec.paths[path][method] = {
      summary: ep.description,
      description: ep.description,
      parameters: parameters,
      responses: {
        "200": {
          description: "Successful response"
        }
      }
    };

    if (ep.auth_required) {
      spec.paths[path][method].security = [{ BearerAuth: [] }];
    }
  });

  return JSON.stringify(spec, null, 2);
}

export function exportToPostman(endpoints, projectName = "Generated API") {
  const collection = {
    info: {
      name: projectName,
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    item: []
  };

  endpoints.forEach(ep => {
    const pathSegments = ep.route.split('/').filter(p => p);
    
    const item = {
      name: `${ep.method} ${ep.route}`,
      request: {
        method: ep.method,
        header: [],
        url: {
          raw: `{{baseUrl}}${ep.route}`,
          host: ["{{baseUrl}}"],
          path: pathSegments
        },
        description: ep.description
      },
      response: []
    };

    if (ep.auth_required) {
      item.request.auth = {
        type: "bearer",
        bearer: [
          {
            key: "token",
            value: "{{authToken}}",
            type: "string"
          }
        ]
      };
    }

    collection.item.push(item);
  });

  return JSON.stringify(collection, null, 2);
}
